---
title: "Gov 50 Final Project"
author: "Dillon Browning"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts/Part I

I am interested in exploring data in a few areas. One could potentially be the correspondence of minimum wage and voter preference or drug overdoses. I am not quite sure what necessarily I want to do quite yet.

## Research Idea/Part II
How does access to transportation in rural counties in America influence drug overdose deaths? In America, there is an expanding gap between rural and suburban/urban Americans in economic, healthcare, and educational outcomes. While numerous different policy proposals beginning with those following the Financial Crisis of 2008 have been proposed, there have been mixed outcomes. Over the past year, there have been many debates in Congress on spending and what programs should be pared down. This year representatives (as often happens) continued to look at reducing funding to rural transportation subsidies that thousands of Americans rely upon not only for an easier connection to the country/world, but businesses and other outcomes rely upon peoples ability to access these transportation networks. Areas with worse access to reliable transportation, I believe, are more likely to have a high drug overdose rate. The explanatory variable is the number of people who use transportation (excluding personal vehicle) in a rural county, while the outcome variable is the number of drug overdoses per capita. If overdoses increase as transportation decreases, that would prove my hypothesis; if overdoses increase as transportation decreases, that would disprove my hypothesis.